name: Build and Notify Discord

on:
  push:
    branches:
      - master # or any branch you want to monitor

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # or your required Java version
          distribution: 'corretto'

      - name: Build Minecraft Mod
        run: |
          chmod +x ./gradlew  # Ensure gradlew is executable
          mkdir -p build/libs
          ./gradlew build

      - name: Create Git Tag
        id: tag
        run: |
          # Create a new tag based on the commit SHA
          TAG_NAME="UserBuild_$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "release_tag=$TAG_NAME" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR file to GitHub Releases
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.release_tag }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the latest commit message
        id: get_commit_message
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Send commit message and download link to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"Hello, I'm a bot set up by Akane. Here's what he has to say:\\nCommit message: ${{ env.message }}\\n\\nDownload the mod: [Minecraft Mod JAR](https://github.com/${{ github.repository }}/releases/${{ env.release_tag }}/download/zombiesurvival-1.0.0+1.20.1.jar )\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
