name: Build and Notify Discord

on:
  push:
    branches:
      - master # or any branch you want to monitor

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # or your required Java version
          distribution: 'corretto'

      - name: Build Minecraft Mod
        run: |
          chmod +x ./gradlew  # Ensure gradlew is executable
          mkdir -p build/libs
          ./gradlew build

      - name: Create Git Tag
        id: tag
        run: |
          # Create a new tag based on the commit SHA
          echo "::set-output name=release_tag::UserBuild_$(date +'%Y%m%d%H%M%S')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR file to GitHub Releases
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the latest commit message
        id: get_commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Send commit message and download link to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "Hello, I\'m a bot set up by Akane. Here\'s what he has to say:\nCommit message: FIxed a java sdk\n\nDownload the mod\: \[Minecraft Mod JAR\](https://github.com/Akane-Dev/ZombieSurvivalQuilt/releases/latest/download/minecraft-mod.jar\)"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
